import {
    BookOpen,
    CheckCircle,
    CircleDot,
    FolderPlus,
    GitBranchMinus,
    GitBranchPlus,
    GitCommit,
    GitFork,
    GitMerge,
    GitPullRequestArrow,
    ListChecks,
    MessageSquare,
    MoreHorizontal,
    Star,
} from "lucide-react";

export const EVENT_ICONS = {
    all: ListChecks,
    push: GitCommit,
    watch: Star,
    create_repo: FolderPlus,
    create_branch: GitBranchPlus,
    delete_branch: GitBranchMinus,
    fork: GitFork,
    wiki: BookOpen,
    issue_open: CircleDot,
    issue_close: CheckCircle,
    pull_open: GitPullRequestArrow,
    pull_close: GitMerge,
    commit_comment: MessageSquare,
    issue_comment: MessageSquare,
    pull_comment: MessageSquare,
    other: MoreHorizontal,
};
